import { jsx as _jsx } from "react/jsx-runtime";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers/Providers";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children, }) {
    return (_jsx("html", { lang: "en", children: _jsx("body", { className: inter.className, children: _jsx(Providers, { children: children }) }) }));
}
//# sourceMappingURL=layout.js.map