import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript } from "./home/components/theme/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>

      <body className={inter.className} >
        <ColorSchemeScript localStorageKey="theme-mode" themeLocalStorageKey="trio-theme" colorType="rgb"


        />
        {/* <Providers>  */}
        {children}
        {/* </Providers> */}
      </body>
    </html>
  );
}
